### ISSUE TITLE
SSH Key management

### ISSUE THREAD

**Issue by tonilaukka** [roots/bedrock-ansible#10]
When you're using multiple SSH Keys it would be nice if you could define the key in group_vars/all. It defaults to ~/.ssh/id_rsa.pub wich I don't have at all and that ends up in an error the first time you run vagrant up. I'm not familiar with ansible, so it took me a while to find out where to set it (roles/capistrano-setup/defaults/main.yml -> deploy_keys), so I could fix the error.

**Comment by swalkinshaw** [comment]
GitHub SSH keys were added in #95.
