### ISSUE TITLE
SMTP server request

### ISSUE THREAD

**Issue by rstormsf** [roots/bedrock-ansible#122]
With current setup, you have no way to use Contact Form or forgot password link because there is no mail server being setup. 

Actually, there are bunch of SMTP plugins so this could be delegated to some other service which I think is the best option which rewrites PHPMailer function

**Comment by swalkinshaw** [comment]
We haven't installed any SMTP clients because we're in favour is using a 3rd party service like Mandrill, Sendgrid, Mailgun etc.

But I do think we should still provide a simple client by default that's only for sending. msmtp and ssmtp both seem simple so I'll leave this issue open until I check them out.

**Comment by rstormsf** [comment]
Do you mind to explain briefly how do you integrate it? Do you using any plugin? How do you reset password from wp-admin?

**Comment by swalkinshaw** [comment]
All of those services are very similar and usually work in 2 ways: either via their API (raw HTTP calls or a PHP client library), or via SMTP (which you'd need a client like you mentioned).

To hook into WP mail there's various plugins. Here's an example of one: https://wordpress.org/plugins/wpmandrill/

This one uses curl in the background for their API so not SMTP needed at all.

In general you should always use an email service for sending external email. It's very hard and not really worth the trouble to setup your own. If it's just for "internal" emails like signups/resets for developers/admin then you don't need to worry.

**Comment by rstormsf** [comment]
but it doesn't solve the problem for reset password link

**Comment by swalkinshaw** [comment]
What doesn't? The Mandrill plugin would work for example.

But as I said I'm leaving this issue open and we'll add an SMPT client which will fix this problem as well. Then emails will work regardless of what solution people use.

**Comment by JulienMelissas** [comment]
I love the Mandrill plugin and service, but :+1: for for SMPT client just in case.

**Comment by nathanielks** [comment]
Can I vote against it? SMTP would feel more like an awkward dongle that will probably fall behind in maintenance. Reason I say this is it appears everyone uses an external service, so why bake it in?

**Comment by austinpray** [comment]
@nathanielks SMTP should be opt-out and not opt-in. We should definitely recommend people use an external service but email not working out of the box by default is unacceptable.

**Comment by mAAdhaTTah** [comment]
Yeah, you need something. I think there was one instance where I added a user, not realizing there was no mail system installed, and the adding process timed out (it worked, the user was added, but it was a very odd experience).
