### ISSUE TITLE
Install npm and Sage packages?

### ISSUE THREAD

**Issue by mAAdhaTTah** [roots/bedrock-ansible#124]
In light of the conversation here: https://github.com/roots/roots/pull/1257, does it make sense to make installing node, npm, bower, & gulp an optional install for deploying a sage theme?

**Comment by swalkinshaw** [comment]
Bedrock and hence this playbook has nothing to do with Roots/Sage. I think the proper solution is for us to create another repo under the Roots org which would be a role to install what's necessary for deploying our theme.

**Comment by nathanielks** [comment]
What if we had a create-your-own-adventure playbook, a playbook that's run specifically for whatever theme you're looking to use? We could create one for sage as a demo. Two birds with one stone.

**Comment by austinpray** [comment]
I agree with @swalkinshaw. Perhaps I can create a teeny tiny buildpack for Sage themes that gives you everything you need + a process.

**Comment by nathanielks** [comment]
Could also be a separate Ansible Galaxy module.

**Comment by swalkinshaw** [comment]
Keep in mind that the only thing required for Sage is Node and maybe globally installing some packages. Everything else will be part of the deployment process which is already in progress at https://github.com/roots/bedrock-ansible/pull/95.

There's also the debate about doing the compiles locally and uploading assets which wouldn't make any of this necessary.

**Comment by mAAdhaTTah** [comment]
> I agree with @swalkinshaw. Perhaps I can create a teeny tiny buildpack for Sage themes that gives you everything you need + a standard process to follow.

Awesome. Really excited about 8.0.0!

> There's also the debate about doing the compiles locally and uploading assets which wouldn't make any of this necessary.

How would you deploy if this was the methodology? Can Ansible copy it up?

**Comment by swalkinshaw** [comment]
@mAAdhaTTah yeah exactly. Ansible can run tasks locally or do local actions and then copy/upload the files.
