### ISSUE TITLE
ansible-playbook

### ISSUE THREAD

**Issue by heyalbert** [roots/bedrock-ansible#127]
nsible_ssh_user":"vagrant","user":"vagrant"} ./site.yml
The executable 'ansible-playbook' Vagrant is trying to run was not
found in the PATH variable. This is an error. Please verify
this software is installed and on the path.

**Comment by nathanielks** [comment]
@heyalbert how did you install ansible on your machine? Homebrew? From source?

**Comment by heyalbert** [comment]
just vagrant up

**Comment by nathanielks** [comment]
So does that mean you haven't installed `ansible` on your machine? Try running `which ansible` and see if it returns anything.

**Comment by heyalbert** [comment]
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
==> default: Mounting NFS shared folders...
==> default: Mounting shared folders...
    default: /vagrant => /Users/als/Sites/PRO/bedrock-ansible
==> default: Bindfs seems to not be installed on the virtual machine
==> default: Fuse kernel module seems to be not loaded, trying to load it
==> default: Creating bind mounts for selected devices
==> default: Creating bind mount from /vagrant-nfs-.......dev to /srv/www/.......dev/current
==> default: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/Users/als/Sites/PRO/bedrock-ansible/.vagrant/machines/default/virtualbox/private_key --user=vagrant --connection=ssh --limit='default' --inventory-file=/Users/als/Sites/PRO/bedrock-ansible/.vagrant/provisioners/ansible/inventory --extra-vars={"ansible_ssh_user":"vagrant","user":"vagrant"} ./site.yml
The executable 'ansible-playbook' Vagrant is trying to run was not
found in the PATH variable. This is an error. Please verify
this software is installed and on the path.
USER@MAC:~/Sites/PRO/bedrock-ansible$ which anisble
USER@MAC:~/Sites/PRO/bedrock-ansible$

**Comment by nathanielks** [comment]
Ah, ok. You haven't installed Ansible yet. Per the [Readme](https://github.com/roots/bedrock-ansible#requirements), Ansible 1.6 or greater is required. [Here's](http://docs.ansible.com/intro_installation.html) how to install it. After that, you should be good to go!
