### ISSUE TITLE
Install Dependencies with Composer failed

### ISSUE THREAD

**Issue by heyalbert** [roots/bedrock-ansible#128]
```
TASK: [wordpress-sites | Install Dependencies with Composer] ******************
failed: [default] => (item={'site_install': True, 'admin_user': 'admin', 'site_name': '.........dev', 'local_path': '../..........dev', 'system_cron': True, 'multisite': {'enabled': False}, 'site_title': 'Example Site', 'user': 'vagrant', 'env': {'db_name': 'example_dev', 'wp_env': 'development', 'db_user': 'example_dbuser', 'db_password': 'example_dbpassword', 'wp_home': 'http://.........dev', 'wp_siteurl': 'http://.............dev/wp'}, 'site_hosts': ['.......dev'], 'group': 'www-data', 'admin_email': 'admin@..........dev', 'admin_password': 'admin'}) => {"changed": true, "cmd": ["composer", "install"], "delta": "0:00:00.056822", "end": "2015-01-29 08:13:55.281499", "item": {"admin_email": "admin@..........dev", "admin_password": "admin", "admin_user": "admin", "env": {"db_name": "example_dev", "db_password": "example_dbpassword", "db_user": "example_dbuser", "wp_env": "development", "wp_home": "http://........dev", "wp_siteurl": "http://........dev/wp"}, "group": "www-data", "local_path": "../........dev", "multisite": {"enabled": false}, "site_hosts": ["...........dev"], "site_install": true, "site_name": ".........dev", "site_title": "Example Site", "system_cron": true, "user": "vagrant"}, "rc": 1, "start": "2015-01-29 08:13:55.224677", "warnings": []}
stdout: Composer could not find a composer.json file in /srv/www/......dev/current
To initialize a project, please create a composer.json file as described in the http://getcomposer.org/ "Getting Started" section

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/als/site.retry

default                    : ok=61   changed=30   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by jurajk** [comment]
@heyalbert how did you solve this? having the same exact problem...

**Comment by deschet** [comment]
@heyalbert I'm also having this issue.  Please let us know how you solved this.  Thanks in advance for sharing!

**Comment by austinpray** [comment]
@heyalbert what's your group_vars/development look like? This is erroring on development right?

**Comment by chredd** [comment]
Having the some problem here. Any solutions yet?

**Comment by fullyint** [comment]
**Development server using vagrant.** Too obvious maybe, but have you confirmed that the `composer.json` is where you expect on the dev server? (e.g., using `vagrant ssh`, `cd /srv/www/example.dev/current` and `ll` -- that path assumes `site_name: example.dev` in `group_vars/development`) 

If `composer.json` is not in that directory, and the other bedrock contents aren't either, it suggests a problem with the vagrant sync folder (syncs your bedrock project folder into vagrant vm). In this case, you could review whether your `site_name` and `local_path` definitions from `group_vars/development` will work with the `config.vm.synced_folder` logic in the `Vagrantfile`. To be safe, avoid using spaces or unusual characters in `site_name` and `local_path`.

**Staging/Production server on remote host.** The bedrock contents, including `composer.json`, won't be on the server the first time you run the `site.yml` playbook. See composer-related discussion in #84, #30, #135 etc.

**Comment by chredd** [comment]
Solved for me. My problem was that github.com wasn't among known_hosts and that I install som packages from there. Adding github.com to known hosts for root in the box solved my problem.

**Comment by swalkinshaw** [comment]
What @fullyint covers this issue so I'm locking this.
