### ISSUE TITLE
Error while provisioning msg: Error while linking: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by intelligence** [roots/bedrock-ansible#132]
While trying to provision my stage I received this error.

    TASK: [wordpress-sites | Create WordPress configuration for Nginx] ************ 
    failed: [x.x.x.x] => (item={'site_install': True, 'admin_user': 'admin', 'site_name': ’sub.domain.com/
    project', 'system_cron': True, 'multisite': {'enabled': False}, 'site_title': ’XXX Staging', 'user': 'deploy', 
    'env': {'db_name': ’xxx_staging', 'wp_env': 'staging', 'db_user': ’xxx_dbuser', 'db_password': ’xxx', 
    'wp_home': 'http://sub.domain.com/project', 'wp_siteurl': 'http://sub.domain.com/project/wp'}, 'site_hosts': 
    ['sub.domain.com/project', ’x.x.x.x’], 'group': 'www-data', 'admin_email': 'admin@staging.example.com', 
    'admin_password': ’xxx’}) => {"failed": true, "item": {"admin_email": "admin@staging.example.com", 
    "admin_password": ”xxx”, "admin_user": "admin", "env": {"db_name": ”xxx_staging", "db_password": 
    ”xxx_dbpassword", "db_user": ”xxx_dbuser", "wp_env": "staging", "wp_home": "http://sub.domain.com/project”, 
    "wp_siteurl": "http://sub.domain.com/project/wp"}, "group": "www-data", "multisite": {"enabled": false}, 
    "site_hosts": ["sub.domain.com/project”, ”x.x.x.x”], "site_install": true, "site_name": "sub.domain.com/
    project”, "site_title": ”XXX Staging", "system_cron": true, "user": "deploy"}}
    msg: Destination directory /etc/nginx/sites-available/sub.domain.com does not exist

    FATAL: all hosts have already failed -- aborting

    PLAY RECAP ******************************************************************** 
               to retry, use: --limit @/Users/me/site.retry

    x.x.x.x             : ok=50   changed=37   unreachable=0    failed=1 

I SSH’ed into the server (as admin user) and sub.domain.com in /etc/nginx/sites-available was indeed missing.

I tried to run mkdir sub.domain.com but got ”permission denied”. I reran with sudo and could then create the folder and then proceeded to retry with the provisioning.

Which gave me this error:

    TASK: [wordpress-sites | Enable WordPress site] ******************************* 
    failed: [x.x.x.x] => (item={'site_install': True, 'admin_user': 'admin', 'site_name': 'sub.domain.com/
    project', 'system_cron': True, 'multisite': {'enabled': False}, 'site_title': ’XXX Staging', 'user': 'deploy', 
    'env': {'db_name': ’xxx_staging', 'wp_env': 'staging', 'db_user': ’xxx_dbuser', 'db_password': ’xxx’, 
    'wp_home': 'http://sub.domain.com/project', 'wp_siteurl': 'http://sub.domain.com/project/wp'}, 'site_hosts': 
    ['sub.domain.com/project', 'x.x.x.x'], 'group': 'www-data', 'admin_email': 'admin@staging.example.com', 
    'admin_password': ’xxx’}) => {"failed": true, "item": {"admin_email": "admin@staging.example.com", 
    "admin_password": ”xxx”, "admin_user": "admin", "env": {"db_name": ”xxx_staging", "db_password": 
    ”xxx_dbpassword", "db_user": ”xxx_dbuser", "wp_env": "staging", "wp_home": "http://sub.domain.com/project", 
    "wp_siteurl": "http://sub.domain.com/project/wp"}, "group": "www-data", "multisite": {"enabled": false}, 
    "site_hosts": ["sub.domain.com/project", "x.x.x.x"], "site_install": true, "site_name": "sub.domain.com/
    project", "site_title": ”XXX Staging", "system_cron": true, "user": "deploy"}, "path": "/etc/nginx/sites-
    enabled/sub.domain.com/project.conf", "state": "absent"}
    msg: Error while linking: [Errno 2] No such file or directory

    FATAL: all hosts have already failed -- aborting

    PLAY RECAP ******************************************************************** 
               to retry, use: --limit @/Users/me/site.retry

    x.x.x.x             : ok=51   changed=2    unreachable=0    failed=1

If I understand it correctly it says project.conf is missing. But it’s there. But the content of the config seems a bit weird.

    server {
      set $site_name sub.domain.com/project;

      listen *:80;
      server_name  sub.domain.com/project 188.166.40.146;
      access_log   /srv/www/sub.domain.com/project/logs/sub.domain.com/project.access.l$
      error_log    /srv/www/sub.domain.com/project/logs/sub.domain.com/project.error.lo$

      root  /srv/www/sub.domain.com/project/current/web;
      index index.php;

      charset utf-8;

      include wordpress.conf;
    }

    server {
      listen *:80;
      server_name www.sub.domain.com/project;
      return 301 $scheme://sub.domain.com/project$request_uri;
    }
    server {
      listen *:80;
      server_name www.x.x.x.x;
      return 301 $scheme://x.x.x.x$request_uri;
    }

I’m thinking specifically of the specs for both server { }, as they have www infront of the server_name. 
I’m coming up with a blank here, any ideas? Maybe it has something to do with that I'm trying to have it running in a subfolder under a sub domain? (The idea is to run multiple Wordpress installs from the same subdomain, thus the subfolder)

Edit: Ok, so the problem is obviously that I'm running sub.domain.com/project instead of just sub.domain.com. But not sure how I get it to run in a subfolder?

Edit2: Unless I go the Multisite route? But as each site will be separate projects rather than subsites to the main site I guess it don't makes a lot of sense?

**Comment by swalkinshaw** [comment]
We'll need to see your group vars file for this environment in order to help debug. Just filter out any passwords or sensitive info.

**Comment by intelligence** [comment]
Ah, yes, sorry. The staging group vars file contains:

    mysql_root_password: xxx

    wordpress_sites:
      - site_name: sub.domain.com/project
        site_hosts:
          - sub.domain.com/project
          - x.x.x.x (my droplet ip)
        user: deploy
        group: www-data
        site_install: true
        site_title: Staging
        admin_user: admin
        admin_password: xxx
        admin_email: admin@staging.example.com
        system_cron: true
        multisite:
          enabled: false
        env:
          wp_home: http://sub.domain.com/project
          wp_siteurl: http://sub.domain.com/project/wp
          wp_env: staging
          db_name: xxx
          db_user: xxx
          db_password: xxx

**Comment by swalkinshaw** [comment]
@intelligence oops forgot about this. `site_name` can't  contain a subdirectory like `/project`. It's just a description name, not an actual URI.

`site_hosts` also can't  contain a subdirectory.
