### ISSUE TITLE
Ansible provision and Capistrano deploy

### ISSUE THREAD

**Issue by JacobDorman** [roots/bedrock-ansible#135]
Until https://github.com/roots/bedrock-ansible/pull/95 or https://github.com/roots/bedrock-ansible/issues/40 are sorted. 

### Field Report
**DigitalOcean - Ubuntu 14.04 x64**

**DO** `cap staging deploy:check`
* **FAIL** `develop user not exist`

**DO** `ansible-playbook -i hosts/staging site.yml -vvvv`
* **FAIL** on `mariadb | Start MariaDB MySQL Server`

    ```
    ssh: connect to host 23.23.23.23 port 22: Connection refused
    ```
    
* has logs? 

    ```
    2015-03-02 07:45:55,627 FAIL2ban.actions: WARNING [ssh] Ban 200.200.200.200
    2015-03-02 07:45:55,638 FAIL2ban.actions.action: ERROR  iptables -n -L INPUT | grep -q `FAIL2ban-ssh[ \t]` returned 100
    2015-03-02 07:45:55,639 FAIL2ban.actions.action: ERROR  Invariant check failed. Trying to restore a sane environment
    2015-03-02 07:45:55,652 FAIL2ban.actions.action: ERROR  iptables -D INPUT -p tcp -m multiport --dports ssh -j FAIL2ban-ssh
    iptables -F FAIL2ban-ssh
    iptables -X FAIL2ban-ssh returned 100
    ```
    
* Auto-Unban _(roll with it)_

    ```
    2015-03-02 07:55:56,151 FAIL2ban.actions: WARNING [ssh] Unban 200.200.200.200
    ```

**DO** `ansible-playbook -i hosts/staging site.yml -vvvv --start-at-task="mariadb | Start MariaDB MySQL Server"`
* **FAIL** on `wordpress-sites | Install Dependencies with Composer`

    ```
    stderr: Composer could not find a composer.json file in /srv/www/sub.domain.tld/current
    ```

**DO** `cap staging deploy:check` **SUCCESS!**

**DO** `cap staging deploy` **SUCCESS!**

**DO** `ansible-playbook -i hosts/staging site.yml -vvvv --start-at-task="wordpress-sites | Install Dependencies with Composer"` **SUCCESS!**

**DO** http://sub.domain.tld/
* **FAIL** `"Welcome to nginx on Debian!"`

**DO** `service php5-fpm restart && service nginx restart`

```
php5-fpm stop/waiting
php5-fpm start/running, process 22925
 * Restarting nginx nginx                                                        [ OK ]
```

**DO** http://sub.domain.tld/ ***SUCCESS!***

https://github.com/roots/bedrock-ansible/issues/84
https://github.com/roots/bedrock-ansible/issues/119
https://discourse.roots.io/t/ansible-provisioning-error-on-server/2416/8

**Comment by swalkinshaw** [comment]
Thanks for this debugging log. Seems like there's at least a new bug with fail2ban and I'll look into.

Another update that will be included with the Ansible deploys is sudoers access for the `deploy` use to reload php-fpm and Nginx.

Note that you should almost always prefer `reload` over `restart` for both those commands although doesn't matter much when the site wasn't working to begin with.

**Comment by swalkinshaw** [comment]
One more thing, it seems you're using the `develop` user for deploying in Cap? You can change the `deploy_user` var to match that and avoid that issue.

**Comment by JacobDorman** [comment]
Yep, that was a mistake. I've changed the user to 'deploy'.

The last provision and deploy went smoothly. 
* didn't run into the issue with fail2ban, but did increase the ferm dport_limit for ssh to ```hits: "20"```. 
* changed ```run_composer: false``` and ```site_install: false```
* ran secure-root.yml playbook before deploy

**Comment by swalkinshaw** [comment]
I've increased the default limit to 20 as well.
