### ISSUE TITLE
Question on .env linking

### ISSUE THREAD

**Issue by alexciarlillo** [roots/bedrock-ansible#137]
This is my first day with bedrock-ansible so apologies if this is a silly question. Why is the .env file from my example.dev site symlinked to a folder structure of the VM? When I first use composer to create a bedrock project, I can modify the .env file. After I do a 'vagrant up' from bedrock-ansible, the .env becomes a link to  '/srv/www/example.dev/shared/.env' but that link exists on the HOST machine, which has no '/srv/www/...' directory. So now, if for some reason I destroy my bedrock-ansible VM, I lose the .env file of my project as it is now symlinked to a file which does not exist. Even if I don't destroy the VM, I cannot edit the .env and re-provision at this point. It is not a big deal to re-create it... but it seems unnecessary. Why not do the symlink in the other direction? Is this how it is supposed to work? If so can someone explain why?

**Comment by mAAdhaTTah** [comment]
Bedrock-ansible creates that file when you provision the VM. It's not necessary to save it because when you destroy your VM and run `vagrant up` again, it'll create a new one.

**Comment by swalkinshaw** [comment]
If you use bedrock-ansible you basically don't need to generate the `.env` through Composer. It's really two separate methods which is a bit confusing. I might just get rid fo the `.env` generation via Composer all together soon.

**Comment by alexciarlillo** [comment]
I see. That is what I get for jumping into Bedrock and bedrock-ansible in the same go. Kind of got myself confused. Thanks
