### ISSUE TITLE
Correct way to setup/provision new (second) development site?

### ISSUE THREAD

**Issue by alexciarlillo** [roots/bedrock-ansible#139]
I am using bedrock-ansible strictly for a dev environment. I got it setup for a single site so far, and now want to add another. I know I need to add the site to group_var/development and then create a new site directory which lives next to bedrock-ansible (e.g. example2.dev). Now can/should I just re-provision the existing VM, or should I destroy and re-create? Or can I just re-run the ansible playbook?

**Comment by swalkinshaw** [comment]
You'd need to do two things:

1. `vagrant reload`
2. `vagrant provision`

Or just re-create the Vagrant box.
