### ISSUE TITLE
Error installing nokogiri (1.6.6.2)

### ISSUE THREAD

**Issue by griffiths** [roots/bedrock-ansible#140]
Hi -
When I run vagrant up I get the following message:
vagrant-bindfs missing, please install the plugin:
vagrant plugin install vagrant-bindfs

When installing vagrant-bindfs, I get the following message:
An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.

I tried `gem install nokogiri -v '1.6.6.2'` which returns:
Successfully installed nokogiri-1.6.6.2

Running vagrant plugin install vagrant-bindfs still returns the error though. Any ideas?
Thanks!

**Comment by fullyint** [comment]
Just to double-check, did you attempt to install the `vagrant-bindfs` plugin using this command: [`vagrant plugin install vagrant-bindfs`](http://docs.vagrantup.com/v2/plugins/usage.html)? I ask because I can't think of why Bundler would be involved in the install process (as noted in the error message).

**Comment by griffiths** [comment]
Yes - `vagrant plugin install vagrant-bindfs`

After running the above I get:

Installing the 'vagrant-bindfs' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.

Thanks again for your help!

**Comment by nathanielks** [comment]
If I remember correctly, this has to do with vagrant and system using different ruby binaries. Are you using RVM or rbenv?



—

**Comment by griffiths** [comment]
RVM

**Comment by griffiths** [comment]
Hi --
Reinstalling Vagrant seemed to fix the issue for me.

One more question -- It seems like every page is returning the WordPress home page (even linked JS/CSS files come back with the default page). Is there something I'm missing in the configuration? I assume this has something to do with the nginx config?

Thanks again for your help!

**Comment by swalkinshaw** [comment]
It could but check to make your WP url settings are correct here: https://github.com/roots/bedrock-ansible/blob/master/group_vars/development#L19-L20

Closing this the original issue is not related to this project in itself.
