### ISSUE TITLE
apt-get update && apt-get upgrade

### ISSUE THREAD

**Issue by rstormsf** [roots/bedrock-ansible#142]
I'm thinking of checking updates on my server and I'm afraid that this can break something.
How do you stay up-to-date?
What if something breaks? 
How to test before applying? Should I just ssh into vagrant and see if it works?

**Comment by swalkinshaw** [comment]
I'd definitely run it on your Vagrant VM first to test it out. If it breaks you can always just re-create it.

But I'm pretty bad about keeping my stuff out to date. Unless I hear about a major vulnerability I usually don't update anything unless I need a new feature.
