### ISSUE TITLE
Why didn't you guys add NPM and Bower support for Sage installation?

### ISSUE THREAD

**Issue by jcroll** [roots/bedrock-ansible#146]
Would you be open to a pr that included provisioning for an environment that met the Sage requirements?

**Comment by retlehs** [comment]
i mentioned this to @swalkinshaw the other day. :+1: 

bedrock box is long overdue for an update

**Comment by mAAdhaTTah** [comment]
Related: #124 & #126. I think the Sage build stuff is going to be fixed once the deploy branch is merged.

**Comment by jcroll** [comment]
If I did open a pr would you be ok with using Ansible Galaxy roles? If yes I imagine your readme would have to get updated with instructions on how to install an ansible galaxy role and additionally I'm not sure how well that would work with your windows ansible script.

Might make more sense just to find a node ansible galaxy role and copy and paste from it.

Additionally I don't see much harm in including these dependencies in your default provisioning.

What do you think?

**Comment by swalkinshaw** [comment]
We're going to be recommending compiling assets locally so none of this software will get installed on the VM.
