### ISSUE TITLE
Unable to upload to directory in development

### ISSUE THREAD

**Issue by dstrunk** [roots/bedrock-ansible#147]
After running `vagrant up` for a development environment, WordPress is unable to import anything (photos, WordPress eXtended RSS (WXR) files, etc).

it was an easy fix on my end—changing the `user = www-data` to `user = vagrant` in file `/etc/php5/fpm/pool.d/wordpress.conf` then reloading php5-fpm was enough to solve it after `vagrant up` had been run.

I can submit a pull request ... adding a conditional to check for `'development' in group_names` in the `roles/wordpress-sites/templates/php-fpm.conf.j2` and `roles/php/templates/php-fpm.conf.j2` files worked on my end.

**Comment by enricodeleo** [comment]
I think it is the same issue as my #150 
The workaround you mentioned works but the drawback is that you cannot use wp-cli from the host (I use https://github.com/xwp/wp-cli-ssh) since the www-data user isn't allowed to ssh into the machine (and is right to leave it as is).

**Comment by swalkinshaw** [comment]
@dstrunk it would be great if you could try this with the `deploys` brach from #95

**Comment by callerc1** [comment]
same issue as @dstrunk using wp-cli-ssh as a workaround works well.

**Comment by swalkinshaw** [comment]
Closing this but feel free to re-open if it still occurs now that #95 has been merged in.
