### ISSUE TITLE
vagrant-hostsupdater not working as expected

### ISSUE THREAD

**Issue by slackday** [roots/bedrock-ansible#165]
Hi,

I've noticed the new syntax for defining wordpress_sites in the latest version of bedrock-ansible.

*Previous syntax:*

    wordpress_sites:
        - site_name:  example.dev
          site_hosts:
              example.dev
          local_path: '../example.dev'
          [more_options]

        - site_name:  test.dev
          site_hosts:
              test.dev
          local_path: '../test.dev'
          [more_options]

*New syntax:*

    wordpress_sites:
        example.dev:
            site_hosts:
                - example.dev
            local_path: '../example.dev'
            [more_options]

        test.dev:
            site_hosts:
                - test.dev
            local_path: '../test.dev'
            [more_options]

I like this new syntax. However when provision the box vagrant-hostupdater is not working as before. It's not longer adding the new sites to the hostfile. Only the first entry which is example.dev.

I noticed this in the vagrantfile config.vm.hostname = main_site.values.first['site_hosts'].first which gives some lead as to what could cause this issue. 

After some playing around I got it working again and found the simplest was to change

    if Vagrant.has_plugin? 'vagrant-hostsupdater'
        host_aliases = other_sites.flat_map { |(_name, site)| site['site_hosts'] }
        config.hostsupdater.aliases = host_aliases - [config.vm.hostname]
    else

*To*

    if Vagrant.has_plugin? 'vagrant-hostsupdater'
        host_aliases = wordpress_sites.flat_map { |(_name, site)| site['site_hosts'] }
        config.hostsupdater.aliases = host_aliases - [config.vm.hostname]
    else

I'm not sure as to why using other_sites don't work and I'm not good enough with Ruby and vagrant to figure out what 

    main_site, *other_sites = wordpress_sites

(with *other_sides) does.

Anyway this worked for me. Would be great if someone could look into this and clearify if this is an issue or just for me.

Thanks!

*edit* fixed formatting

**Comment by swalkinshaw** [comment]
Good catch. There was definitely a little/gap in logic with that. It was also pretty confusing and you made me realize there's a much simpler solution. I've just updated it in <hash>. Thanks!

FYI: `main_site, *other_sites = wordpress_sites`

Just means assign the first element of the array/hash to `main_site`, and all the others to `other_sites`:

```ruby
>> first, *rest = [1,2,3,4]
>> first
=> 1
>> rest
=> [2, 3, 4]
```

**Comment by slackday** [comment]
Cool, and thanks for explaining that.
