### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by wwbituse1** [roots/bedrock-ansible#169]
I want to use [Sourcegraph](https://sourcegraph.com) for bedrock-ansible code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/roots/bedrock-ansible. (It should only take 30 seconds.)

Thank you!

**Comment by swalkinshaw** [comment]
I figured why not and went through the process. But unfortunately Sourcegraph requires read and write access for hooks and commit statuses. For some reason GitHub also includes that access for my private organizations which for some reason allow 3rd party access (and I don't manage them). For that reason I'm not comfortable giving Sourcegraph access.

Hopefully I'm not mistaken about this:

![screenshot 2015-04-08 23 24 30](https://cloud.githubusercontent.com/assets/295605/7059919/74406c38-de46-11e4-80cc-e3a8a07693ba.png)
