### ISSUE TITLE
Set php fpm user to web_user

### ISSUE THREAD

**Issue by fullyint** [roots/bedrock-ansible#174]
#95 changed the php-fpm `listen.owner` and `listen.group` ([lines](https://github.com/roots/bedrock-ansible/commit/373fe77e90e5208fc96a9def301bb9e17b66f2ac#diff-97894dad9044d33182d3b1ad613c6e20L3)) but I wonder if it should have changed the `user` and `group` instead. I think it caused the issues with permissions on the uploads folder [here](https://discourse.roots.io/t/unable-to-create-directory-uploads-2015-03-is-its-parent-directory-writable-by-the-server/3304) and [here](https://discourse.roots.io/t/cant-upload-images/3450) and likely in #150 as well.

Here's my best guess at what's going on. When someone tries to upload a file, I'm guessing php-fpm acts on their behalf to write a new file to the uploads directory. The permissions on the uploads directory are 0755 so only the owner can write, and the owner is probably `web` (the default `web_user`). However, php-fpm is acting as `www-data` (`user` in `roles/php/templates/php-fpm.conf.j2`), so it is denied permission and can't write.

So, when stefanlindberg ([here](https://discourse.roots.io/t/unable-to-create-directory-uploads-2015-03-is-its-parent-directory-writable-by-the-server/3304)) added `user = {{ web_user }}` it resolved the problem. I propose a slightly different revision, which works in my tests (`roles/php/templates/php-fpm.conf.j2`): 
```diff
- listen.owner = {{ web_user }}
- listen.group = {{ web_group }}
+ listen.owner = www-data
+ listen.group = www-data
- user = www-data
- group = www-data
+ user = {{ web_user }}
+ group = {{ web_group }}
```

```
                          ------- user --------
                              web    www-data 
                          ---------------------
listen.owner  |      web |   Works     fails  
              | www-data |   Works     fails 
```
(got the results above whether `nginx_user` is `web` or `www-data` in `roles/nginx/templates/nginx.conf.j2`).

**Comment by swalkinshaw** [comment]
Yeah this makes sense. Want to do a PR?

**Comment by fullyint** [comment]
I've invited [stefanlindberg](https://discourse.roots.io/t/unable-to-create-directory-uploads-2015-03-is-its-parent-directory-writable-by-the-server/3304/6) to submit the PR after having tracked down the issue. I'll submit it after a while if no response. If it starts to feel urgent, let me know.

**Comment by swalkinshaw** [comment]
Closed via https://github.com/roots/bedrock-ansible/pull/175

**Comment by fabianhenzler** [comment]
having the same issue with the recent master

**Comment by rmartin** [comment]
Confirming that we're seeing this issue as well with the latest version of Trellis. On our end the owner:group was root:root for the uploads folder. Manually changing that to web:www-data worked but I was unclear how to adjust the changes in the new users.yml file to account for that in the initial provision step.

**Comment by fullyint** [comment]
@rmartin I believe that in the original issue of this thread, the `uploads` directory had the expected ownership of `web:www-data` but the php process was running as the user `www-data`, and thus not having permission to upload things on users' behalf.

Your situation sounds different. Apparently your `uploads` directory doesn't have the expected ownership of `web:www-data`, but has `root:root` instead.

Can you help me replicate? Here's what I tried and I still got `web:www-data`. I also was able to upload an image via `wp-admin/media-new.php`.

```
# create DO droplet then set ip to variable
export DO_IP=xx.xx.xx.xxx
# also add IP and staging.example.com to /etc/hosts

# create project dir
cd /tmp
mkdir example.com
cd example.com

# add bedrock
git clone --depth=1 git@github.com:roots/bedrock.git site

# add trellis
git clone --depth=1 git@github.com:roots/trellis.git ansible
cd ansible
ansible-galaxy install -r requirements.yml
sed -i '' "s/192.168.50.5/$DO_IP/g" hosts/staging

# provision and deploy
ansible-playbook -i hosts/staging server.yml
./deploy.sh staging example.com

# check owner:group

ssh root@$DO_IP 'ls -al /srv/www/example.com/current/web/app'
# lrwxrwxrwx 1 web www-data   35 Sep  1 00:39 uploads -> /srv/www/example.com/shared/uploads

ssh root@$DO_IP 'ls -al /srv/www/example.com/shared'
#drwxr-xr-x 3 web www-data 4096 Sep  1 00:43 uploads
```
