### ISSUE TITLE
Ansible requirements required before `vagrant up`

### ISSUE THREAD

**Issue by mAAdhaTTah** [roots/bedrock-ansible#178]
`ansible-galaxy install -r requirements.yml -p vendor/roles` needs to be run before running `vagrant up`. Should this just be fixed in the docs or added to the Vagrantfile?

**Comment by swalkinshaw** [comment]
It's already in the Installation part of the README: https://github.com/roots/bedrock-ansible#installation

**Comment by mAAdhaTTah** [comment]
derp
