### ISSUE TITLE
Ansible-galaxy vendor roles installation failure - not found

### ISSUE THREAD

**Issue by ramielbarsoum** [roots/bedrock-ansible#181]
When attempting to install the ansible galaxy I get the following output

`ansible-galaxy install -r requirements.yml -p vendor/roles`

```
 downloading role 'project_deploy_module', owned by -%20src%3A%20f500
Sorry, - src: f500.project_deploy_module was not found on galaxy.ansible.com.
 downloading role '-%20name%3A%20ntp', owned by 
Sorry, - name: ntp was not found on galaxy.ansible.com.
 downloading role 'ntp', owned by src%3A%20resmo
Sorry, src: resmo.ntp was not found on galaxy.ansible.com.
 downloading role '-%20name%3A%20logrotate', owned by 
Sorry, - name: logrotate was not found on galaxy.ansible.com.
 downloading role 'logrotate', owned by src%3A%20nickhammond
Sorry, src: nickhammond.logrotate was not found on galaxy.ansible.com.
 downloading role '-%20name%3A%20php5-xdebug', owned by 
Sorry, - name: php5-xdebug was not found on galaxy.ansible.com.
 downloading role 'php5-xdebug', owned by src%3A%20MaximeThoonsen
Sorry, src: MaximeThoonsen.php5-xdebug was not found on galaxy.ansible.com.'
```

However, I am able to install the roles manually through:

`ansible-galaxy install f500.project_deploy_module -p vendor/roles`

```
ansible-galaxy install resmo.ntp -p vendor/roles
ansible-galaxy install nickhammond.logrotate -p vendor/roles
ansible-galaxy install MaximeThoonsen.php5-xdebug -p vendor/roles
```

I went in and manually renamed the folders to what is specified in the `requirements.yml`

Not sure what is causing this. But I believe I am able to run without it now.

**Comment by swalkinshaw** [comment]
Judging from the errors it seems like your Ansible doesn't like the `requirements.yml` format which leads me to believe it's an issue with your Ansible version.

What version are you running? We require at least 1.8 now.

**Comment by ramielbarsoum** [comment]
Scott, spot on, sorry I missed this, as I thought my installation was pulling from the ansible ppa, looks like it was not and instead I am installed off the OS repo. Thanks for your time brother. And thank you for creating such a wonderful software!

**Comment by mohsinr** [comment]
Wow @swalkinshaw  thank you for hinting about version. I installed on Ubuntu 14.04 and default version they installed was outdated. 

I upgraded the Ansible version and those errors go away. Thank you!

PS. For anyone facing same issue I added following repo for latest version:
sudo apt-add-repository ppa:ansible/ansible
