### ISSUE TITLE
Multisite Wiki Out of Sync with new commits

### ISSUE THREAD

**Issue by ramielbarsoum** [roots/bedrock-ansible#183]
-  if Vagrant.has_plugin? 'vagrant-hostsupdater'
    -    host_aliases = other_sites.flat_map { |(_name, site)| site['site_hosts'] }
    -    config.hostsupdater.aliases = host_aliases - [config.vm.hostname]

Is now:

    -  if Vagrant.has_plugin? 'vagrant-hostsupdater'
    -    config.hostsupdater.aliases = aliases`

And:

    +    host_aliases = other_sites.flat_map { |site| site['site_hosts'] }

Is now:
`+    host_aliases = wordpress_sites.flat_map { |site| site['site_hosts'] }`

Also
`uninitialized constant PRIVATE_IP`
Should most likely declare an IP instead? '192.168.50.5'

**Comment by swalkinshaw** [comment]
Updated, thanks.
