### ISSUE TITLE
Implement microcaching

### ISSUE THREAD

**Issue by louim** [roots/bedrock-ansible#186]
Hello guys, 

I would to get feedback on implementing microcaching in Bedrock-Ansible. I recently implemented it for the first time on a Bedrock, following instruction from http://reviewsignal.com/blog/2014/06/25/40-million-hits-a-day-on-wordpress-using-a-10-vps/ and it does help tredemously with sudden traffic spikes. Since the cache time is really low, there is no need to implement a flushing mecanism.

The way I see this working could be two settings: 
- Enabled or disabled
- cache time (recommended amount would be around 30 seconds)

Would you be interested in such pull request? I think it will provide added value, with little drawback, but I wanted to have your opinions before doing such thing.

**Comment by retlehs** [comment]
thanks for bringing this up, we are open to this! @swalkinshaw might follow up later with some more details.

**Comment by louim** [comment]
I believe this can be closed :smile:
