### ISSUE TITLE
Documentation on those lines - "generateme" salt

### ISSUE THREAD

**Issue by rstormsf** [roots/bedrock-ansible#192]
What are those lines used for?
```
      auth_key: "generateme"
      auth_salt: "generateme"
      logged_in_key: "generateme"
      logged_in_salt: "generateme"
      nonce_key: "generateme"
      nonce_salt: "generateme"
      secure_auth_key: "generateme"
      secure_auth_salt: "generateme"

```
how to generate it?
Please provide any helpful links either in comments or README.md

**Comment by swalkinshaw** [comment]
It's the standard WP salts: https://codex.wordpress.org/Editing_wp-config.php#Security_Keys

WP has a page to generate them: https://api.wordpress.org/secret-key/1.1/salt/

**Comment by rstormsf** [comment]
Great! Thanks! Please add it to the comments.

**Comment by austinpray** [comment]
@rstormsf https://help.github.com/articles/using-pull-requests/

**Comment by swalkinshaw** [comment]
Closed by https://github.com/roots/bedrock-ansible/pull/196
