### ISSUE TITLE
How to run server.yml playbook to update old ansible playbook

### ISSUE THREAD

**Issue by rstormsf** [roots/bedrock-ansible#197]
So, I have locked down `root` user on my DO instance which I used a repo from 2-3 months old bedrock-ansible.
Now I want to update it and remote user in `server.yml` is `root`. If I change to the sudoers one, it doesn't work because `Update Apt` is ran without sudo. what is good way of updating instance with up-to-date ansible book?

**Comment by swalkinshaw** [comment]
You just need to update `server.yml` with your sudoers user (which I think you did) and add the following:

`sudo: True`

**Comment by rstormsf** [comment]
aha!
