### ISSUE TITLE
Document Ferm usage

### ISSUE THREAD

**Issue by louim** [roots/bedrock-ansible#200]
I think that this: https://github.com/roots/bedrock-ansible/blob/master/group_vars/all#L32
is really dangerous. I didn't check the indentation and assumed it was used to disable Ferm. Result, I'm now locked out of my instance. I think it should have at least an inline comment. 

What do you think?

**Comment by nathanielks** [comment]
@louim I know this isn't the permanent answer you're looking for, but a temporary solution in the mean time is to reboot the server. That'll clear the IPTables rule blocking your specific IP.

**Comment by swalkinshaw** [comment]
If you have a web console or something where you can access the server, you can run `ferm --flush /etc/ferm/ferm.conf`

**Comment by louim** [comment]
@nathanielks I tried rebooting the instance, but alas, that didn't clear the iptable rules. @swalkinshaw Since the instance is locked (SSH key access only), the web console trick didn't work. I ended up rebuilding the instance.

So, what would be the best option? Maybe remove the option from the `all`file, and keep it documented so people changing this parameter will really know what they're doing?

**Comment by swalkinshaw** [comment]
@louim yeah it might be best to remove it. I assume that's the default anyway?

**Comment by louim** [comment]
@swalkinshaw it's indeed the case. Since this is one of the more important rule (allowing SSH connection), and it normally default to false, I made pull request #211 to remove the option.

**Comment by louim** [comment]
I think this can be closed, as Fern is already well documented in it's role folder and #211 has been merged.
