### ISSUE TITLE
Static IP causes issues on shared projects

### ISSUE THREAD

**Issue by kalenjohnson** [roots/bedrock-ansible#202]
A colleague and I are working on a project together. We're running into the issue where the default Vagrantfile works fine for me, but for him, his local network is set up with [24-bit block IP's](http://en.wikipedia.org/wiki/Private_network#Private_IPv4_address_spaces), IE.: `10.*.*.*`

Our current solution is to make the stock `Vagrantfile` a `Vagrantfile.example` and gitignore the `Vagrantfile` so we can modify the IP address as needed. This however creates an issue if we ever want to update the Vagrantfile.

I know `dhcp` won't work with the [bindfs plugin](https://github.com/gael-ian/vagrant-bindfs), but perhaps we can find a way to check the network and assign a static IP that way?

**Comment by swalkinshaw** [comment]
Not sure it's really possible to determine this dynamically without DHCP.

From Vagrant docs:

> It is up to the users to make sure that the static IP doesn't collide with any other machines on the same network.

So it's still up to the user to ensure this. We'd just be setting one at random.

**Comment by kalenjohnson** [comment]
Yeah I see that can be an issue. I would say maybe it could be a modifiable environment variable so the Vagrantfile could be under version control but be able to change the IP address, but I'm not sure how that works in Ruby/Vagrant.

**Comment by mAAdhaTTah** [comment]
@kalenjohnson [This conversation](https://github.com/roots/bedrock-ansible/pull/180#issuecomment-92584084) might help.

**Comment by kalenjohnson** [comment]
That is helpful, thanks @mAAdhaTTah
