### ISSUE TITLE
Start php5-fpm service - Failing

### ISSUE THREAD

**Issue by riveramauro** [roots/bedrock-ansible#205]
I'm getting the following error when running `vagrant provision`.
Here is the log:
```
TASK: [php | Add PHP 5.6 PPA] ************************************************* 
ok: [default]

TASK: [php | Install PHP 5.6] ************************************************* 
ok: [default] => (item=php5-common,php5-fpm,php5-mysqlnd,php5-xmlrpc,php5-mcrypt,php5-curl,php5-gd,php5-cli,php-pear,php5-dev,php5-imap)

TASK: [php | Start php5-fpm service] ****************************************** 
failed: [default] => {"failed": true}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/mauriciorivera/dev.retry

default                    : ok=29   changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
Cloned the repo, and testing this new setup for the first time. Can't seem to figure what this error is. Any clues? Thanks.

**Comment by kalenjohnson** [comment]
I bet you're on Ansible 1.9.1

**Comment by riveramauro** [comment]
Yes I am.... and I just notice "Ansible >= 1.8" in the documentation -_-

Could that be the reason?

**Comment by kalenjohnson** [comment]
Nope, this: https://github.com/ansible/ansible/issues/10675

Either downgrade to 1.9.0.1 or remove these lines: https://github.com/roots/bedrock-ansible/blob/master/roles/php/tasks/main.yml#L20-21

**Comment by riveramauro** [comment]
Can confirm. Downgraded to 1.9.0.1 and working as expected. Thanks!

**Comment by swalkinshaw** [comment]
Leaving this open since it's technically a bug, just not ours. But we'll keep track of it through here.

**Comment by swalkinshaw** [comment]
Closing this since it's been fixed in next Ansible release. `1.9.1` will forever be broken and that note about it will need to be left in the `README` for a little bit.
