### ISSUE TITLE
Wrong path in Vagrant file and missing ntp role

### ISSUE THREAD

**Issue by developdaly** [roots/bedrock-ansible#209]
After running `vagrant up` I get this error...

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

ansible provisioner:
* `playbook` for the Ansible provisioner does not exist on the host system: /my/example.com/dev.yml
```

... so I changed the path from this https://github.com/roots/bedrock-ansible/blob/master/Vagrantfile#L59 to this...

```
 ansible.playbook = File.join(ANSIBLE_PATH, 'ansible/dev.yml')
```

... which then leads to this error ...

```
ERROR: cannot find role in /my/example.com/ansible/roles/ntp or /my/example.com/ansible/ntp or /my/example.com/vendor/roles/ntp
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I can't get provisioning to complete successfully.

**Comment by swalkinshaw** [comment]
What exactly does your folder structure look like (at a high level)?

**Comment by developdaly** [comment]
```
example.com/
- ansible/
- site/
- Vagrantfile
```

**Comment by swalkinshaw** [comment]
Looks correct. Is your `Vagrantfile` like this one: https://github.com/roots/roots-example-project.com/blob/master/Vagrantfile?

**Comment by swalkinshaw** [comment]
Oh I see the problem. You edited `ansible.playbook` instead of the top level constant `ANSIBLE_PATH`.

Follow the link I posted above for the correct solution. I'll be adding a fix soon to make `Vagrantfile` detect your ansible path automatically which will eliminate the need to manually change it.
