### ISSUE TITLE
Update for windows breaks vagrant provisioning on Mac

### ISSUE THREAD

**Issue by evanfuture** [roots/bedrock-ansible#217]
The commit at https://github.com/roots/bedrock-ansible/commit/3d328563858518e75ee0ce60c6f34237f0c5bae0 breaks non-Windows provisioning for more than one site. In order to get sites working, I had to rollback the changes to roles/wordpress-install/tasks/main.yml

Specifically, the dest="/tmp/.env.temp" gives an error of unable to find, does not exist.  Also, the .env file is rewritten with the info from the last site in the setup.

**Comment by swalkinshaw** [comment]
Fixed by 8f14013

**Comment by swalkinshaw** [comment]
Thanks for the report
