### ISSUE TITLE
Make playbooks idempotent

### ISSUE THREAD

**Issue by swalkinshaw** [roots/bedrock-ansible#218]
A few tasks **always** result in `changed` instead of `ok` when re-run. `changed_when` needs to be added for these tasks.

**Comment by mAAdhaTTah** [comment]
*googles "idempotent"*

**Comment by swalkinshaw** [comment]
Fixed in:

* df091c5
* 41dc1c0
* aa02388

There should be only 1 task remaining which isn't idempotent which is due to an [Ansible bug](https://github.com/ansible/ansible-modules-core/issues/1118).
