### ISSUE TITLE
Intermittent dev server connectivity

### ISSUE THREAD

**Issue by davekiss** [roots/bedrock-ansible#221]
Hey guys, great work as always.

Running a site locally with ~~bedrock-ansible~~ Trellis™ will occasionally load fine, but will regularly then return ERR_EMPTY_RESPONSE in Chrome and "server unexpectedly dropped the connection" in Safari.

Happy to provide any logs that might hint at what is happening here if you can point me in the right direction!

**Comment by davekiss** [comment]
No idea here.... destroyed and reinstantiated the vagrant box and it went away

**Comment by evanfuture** [comment]
I've run into this as well.  I think it just has to do with saving files.  I'm used to a quick: Save, Cmd+Tab, Cmd+R, and I must be moving faster than the VM can fnter than the VM can finish saving the file.  Goes away if you wait or if you refresh the browser again.

**Comment by nathanielks** [comment]
In this event, it also helps to restart the php process. `vagrant ssh` and execute `sudo service php7.0-fpm restart`
