### ISSUE TITLE
Redundant item.key when naming log files in wordpress-site.conf.j2?

### ISSUE THREAD

**Issue by nathanielks** [roots/bedrock-ansible#223]
Curious why we prepend the logs with the site name when, in theory, the logs have already been namespaced by the directory it's in?

Ref: https://github.com/roots/bedrock-ansible/blob/master/roles/wordpress-setup/templates/wordpress-site.conf.j2#L11

**Comment by swalkinshaw** [comment]
Think this was just a regression that happened during the big deploy refactor. Shouldn't be there twice though.

**Comment by nathanielks** [comment]
:+1:

**Comment by nathanielks** [comment]
PR incoming

**Comment by swalkinshaw** [comment]
Closed via https://github.com/roots/bedrock-ansible/pull/224
