### ISSUE TITLE
Lost strip_www option when not using SSL

### ISSUE THREAD

**Issue by louim** [roots/bedrock-ansible#229]
Hello,

With the change to support SSL, it looks like we lost the option to strip www when not using SSL
https://github.com/roots/bedrock-ansible/commit/62fbf956618d17753dfdcf449bc33ad4a6c22bac#diff-0d8f97b3067c54fe0b564ce539dbed5fL31

Was this intended? I think I was an useful feature.

**Comment by swalkinshaw** [comment]
Yeah unfortunately it was on purpose. But mostly because the combination of supporting `strip_www` and https redirects was getting really complicated in the template. Pre-https support it was fine.

If there's a clean/good way of implementing this again I'm open to re-adding it.

**Comment by swalkinshaw** [comment]
Re-added in https://github.com/roots/bedrock-ansible/pull/248
