### ISSUE TITLE
Getting "readme not found" when trying to call ansible-galaxy install

### ISSUE THREAD

**Issue by jimmyandrade** [roots/bedrock-ansible#232]
When I call "ansible-galaxy install -r requirements.yml" inside my ansible/ directory, I get the following error:

`ERROR! Could not open readme: [Errno 2] No such file or directory: '/Library/Python/2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/galaxy/data/readme'`

How could I fix this?

**Comment by louim** [comment]
It appear from your error that you are running Ansible 2.0. I believe it is still in development. The preferred way to install Ansible assuming you are on a Mac is via Pip: http://docs.ansible.com/intro_installation.html#latest-releases-via-pip

i also think the latest stable release still has a bug in it #205 so I recommend installing 1.9.0.1

`sudo pip install ansible=1.9.0.1` should do the trick. Check if you still have the error after.

**Comment by dhuyvetter** [comment]
I am getting the same eror. I am using Ansible 2.0 because if I install using the ppa:ansible/ansible  repository, this has version 1.9.1 and the one in the officia Ubuntu repositories is 1.7.2, which is too old. How can I install Ansible 1.9.0.1?

**Comment by dhuyvetter** [comment]
I tried `sudo pip install ansible=1.9.0.1` but it throws an error: 

> ValueError: ('Expected version spec in', 'ansible=1.9.0.1', 'at', '=1.9.0.1')

I got 1.9.0.1 source with `git clone git://github.com/ansible/ansible.git -b v1.9.0-1 --recursive` and built with `make deb` and that worked.

**Comment by swalkinshaw** [comment]
Not sure why the ansible PPA is defaulting to an unreleased version of Ansible. But thanks for posting your fix :+1:

**Comment by dhuyvetter** [comment]
That should be `git clone git://github.com/ansible/ansible.git -b v1.9.0.1-1` to get 1.9.0.1.

**Comment by sebastianneubauer** [comment]
I get this same error with the newly released version 2.0.0.0 on pypi...

**Comment by bbatsche** [comment]
Same. Fresh installs of Ansible 2.0 stable are giving me this error on both OS X 10.10 and Ubuntu 14.04

**Comment by swalkinshaw** [comment]
@sebastianneubauer @bbatsche see https://github.com/ansible/ansible/issues/13419

Downgrade to 1.9.4 for now or follow the manual fix in https://github.com/ansible/ansible/issues/13419#issuecomment-170979499
