### ISSUE TITLE
bedrock-ansible 0.4.0 -- 'site' is undefined -- deploy.yml

### ISSUE THREAD

**Issue by saturday** [roots/bedrock-ansible#233]
I'm attempting to deploy to a staging server and I'm encountering the following error on the deploy task:

```
TASK: [deploy | Initialize] *************************************************** 
<000.000.000.000>
fatal: [000.000.000.000] => One or more undefined variables: 'site' is undefined

FATAL: all hosts have already failed -- aborting
```

I tried to dig around for some hint of where it should be declared but I can't find much. Where should site be declared and what should its value be?

**Comment by retlehs** [comment]
https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md#using-the-issue-tracker

> Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/)).

**Comment by saturday** [comment]
@retlehs This isn't a personal support request. Out of the box bedrock-ansible's deploy playbook expects the existence of a variable called 'site', which appears to never be declared anywhere.

**Comment by retlehs** [comment]
bedrock-ansible 0.4.0 doesn't have any deploy functionality or a deploy.yml file...

**Comment by saturday** [comment]
My apologies. I meant the most recent commit from the master branch (I assumed they were related).

**Comment by saturday** [comment]
Perhaps the site variable should have a default value?

**Comment by retlehs** [comment]
this is a personal support request. you're trying to deploy incorrectly. post on discourse (or read the readme) — i'm locking this thread.

the whole point of using discourse is so that we don't have to back-and-forth on github since lots of people are getting email notifications for these comments.
