### ISSUE TITLE
Add NGINX rewrite for historical /wp-XXXX/ routes

### ISSUE THREAD

**Issue by roosterpark-porch** [roots/bedrock-ansible#236]
We will be prepping a pull request that adds nginx rewrite rules for all the historical /wp-xxxx/ routes. 

While it is understood that the 'correct' url to access wp-admin is `/wp/wp-admin` adding an nginx rewrite rules to handle this eases the transition for editors / writers. This is a relatively major issue as the wp-admin javascripts aggressively use javascript to rewrite URLs based on source / host values.

**Comment by kalenjohnson** [comment]
> This is a relatively major issue as the wp-admin javascripts aggressively use javascript to rewrite URLs based on source / host values.

I'm not aware of what you mean by this. Can you elaborate?

**Comment by swalkinshaw** [comment]
Might want to hold off on the PR.

We don't see how this is an issue with the `/wp/` sub-directory. Putting WP in a sub-directory is an old, well-known practice which isn't Bedrock specific (see https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory and https://github.com/markjaquith/WordPress-Skeleton).

**Comment by mAAdhaTTah** [comment]
> I'm not aware of what you mean by this. Can you elaborate?

Some people write javascript assuming the admin folder is located in `/wp-admin/`. On the BE, you have `get_admin_url` to provides the correct url, but there's no equivalent on the FE. However, assuming the location of the admin dir is `_doing_it_wrong`.

**Comment by kalenjohnson** [comment]
> Some people write javascript assuming the admin folder is located in /wp-admin/. On the BE, you have get_admin_url to provides the correct url, but there's no equivalent on the FE. However, assuming the location of the admin dir is _doing_it_wrong.

Well the same thing can happen with poorly coded plugins written in PHP that don't use the correct functions.

IMO it's not really a reason to add rewrites to the project. @roosterpark-porch also alluded to the fact that JavaScript in WordPress itself relies on having WP in the root directory, which I have never seen personally and wanted some clarification.

**Comment by roosterpark-porch** [comment]
Here's an example of where wordpress rewrites the url in the browser window. This can cause authors to be unable to create new posts in the event that there is a forward proxy rewriting URLs. 

That issue is unrelated, but it is an example of the case I was indicating above

`/wp-admin/includes/misc.php `

```php
function wp_admin_canonical_url() {
. 
.
.
	// Ensure we're using an absolute URL.
	$current_url  = set_url_scheme( 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] );
	$filtered_url = remove_query_arg( $removable_query_args, $current_url );
	?>
	<link id="wp-admin-canonical" rel="canonical" href="<?php echo esc_url( $filtered_url ); ?>" />
	<script>
		if ( window.history.replaceState ) {
			window.history.replaceState( null, null, document.getElementById( 'wp-admin-canonical' ).href + window.location.hash );
		}
	</script>
<?php
}
add_action( 'admin_head', 'wp_admin_canonical_url' );


```

### Full method for posterity:
```php 
function wp_admin_canonical_url() {
	$removable_query_args = array(
		'message', 'settings-updated', 'saved',
		'update', 'updated', 'activated',
		'activate', 'deactivate', 'locked',
		'deleted', 'trashed', 'untrashed',
		'enabled', 'disabled', 'skipped',
		'spammed', 'unspammed',
	);

	/**
	 * Filter the list of URL parameters to remove.
	 *
	 * @since 4.2.0
	 *
	 * @param array $removable_query_args An array of parameters to remove from the URL.
	 */
	$removable_query_args = apply_filters( 'removable_query_args', $removable_query_args );

	if ( empty( $removable_query_args ) ) {
		return;
	}

	// Ensure we're using an absolute URL.
	$current_url  = set_url_scheme( 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] );
	$filtered_url = remove_query_arg( $removable_query_args, $current_url );
	?>
	<link id="wp-admin-canonical" rel="canonical" href="<?php echo esc_url( $filtered_url ); ?>" />
	<script>
		if ( window.history.replaceState ) {
			window.history.replaceState( null, null, document.getElementById( 'wp-admin-canonical' ).href + window.location.hash );
		}
	</script>
<?php
}
add_action( 'admin_head', 'wp_admin_canonical_url' );

```

**Comment by mAAdhaTTah** [comment]
> Well the same thing can happen with poorly coded plugins written in PHP that don't use the correct functions.

Yes, except there are built in WP functions for dealing with this in PHP, but nothing (that I've seen) for doing in JS.

> IMO it's not really a reason to add rewrites to the project.

Agreed.

**Comment by swalkinshaw** [comment]
@roosterpark-porch I don't see how that code that would cause any issues.

```js
document.getElementById( 'wp-admin-canonical' ).href
=> "https://roots.io/wp/wp-admin/index.php"
```

And `$_SERVER['REQUEST_URI']` would also include the `/wp/` subdirectory.

Am I missing something?

**Comment by swalkinshaw** [comment]
Closing as we can't a bug with this.
