### ISSUE TITLE
SSL Logjam attack. Generate strong Diffie-Hellman group

### ISSUE THREAD

**Issue by louim** [roots/bedrock-ansible#252]
We should use a strong Diffie-Hellman: https://weakdh.org/

What should be done: https://weakdh.org/sysadmin.html, We currently enforce ciphers, would shoud just generate a strong Diffie-Hellman group.

Reference SSL labs score for a website deployed using the current configuration: https://www.ssllabs.com/ssltest/analyze.html?d=strategiemaritime.gouv.qc.ca

I will provide a PR

**Comment by swalkinshaw** [comment]
Good find. Definitely a recent update as the current config used to get A+.

**Comment by louim** [comment]
Yeah, it's really recent: https://blog.cloudflare.com/logjam-the-latest-tls-vulnerability-explained/

**Comment by louim** [comment]
PR is up: #253
