### ISSUE TITLE
What about this Anistrano?

### ISSUE THREAD

**Issue by enricodeleo** [roots/bedrock-ansible#255]
Hi everyone, I accidentally found this project https://github.com/ansistrano/deploy anyone has tried it already? Seems to be useful in a Bedrock Ansible environment

**Comment by louim** [comment]
Such deploy mechanism is already implemented in bedrock-ansible (Trellis) using https://github.com/f500/ansible-project_deploy. It provides roughly the same functionalities.

**Comment by enricodeleo** [comment]
Thank you for your reply @louim I was wondering it that was better or not since I personally chosen to stay with Capistrano when the project included ansible deploys at first.

**Comment by swalkinshaw** [comment]
ansistrano looks interesting and there might be some stuff we can copy from it. But the deploy role we already have is using https://github.com/f500/ansible-project_deploy_module which is actually going to be merged into Ansible modules: https://github.com/ansible/ansible-modules-extras/pull/110

**Comment by swalkinshaw** [comment]
Also our current deploy role is pretty close to Capistrano anyway. The f500 project is also modelled after the Capistrano workflow.
