### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by swalkinshaw** [roots/bedrock-ansible#38]
Ideally this playbook should support SSL seamlessly. This includes:

* Getting the certificates/keys onto the server somehow
* Configuring Nginx to use SSL
* Using a proper, modern SSL setup on Nginx (such as https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/directive-only/ssl.conf)
* Should score an A+ on https://www.ssllabs.com/ssltest/
* Proper redirects if SSL is enforced with HSTS headers

**Comment by rstormsf** [comment]
just heads up - don't forget to use latest OpenSSL http://securityaffairs.co/wordpress/34991/security/openssl-announce-new-releases.html

**Comment by swalkinshaw** [comment]
@rstormsf thanks for that.

An update to this issue: I've done most of the work necessary for this on https://roots.io. So it's just a matter of porting that over to here and cleaning it up a bit. And figuring out the best way to deal with certificates.

**Comment by rstormsf** [comment]
@swalkinshaw where can I see instructions for SSL setup?

**Comment by swalkinshaw** [comment]
@rstormsf when a PR is created soon :)

**Comment by rstormsf** [comment]
I mean -  can you share some steps?

**Comment by rstormsf** [comment]
Here is how I did it:

```
cd /etc/nginx
mkdir ssl
cd ssl
openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
```
copy/paste your cert and private key to `/etc/nginx/ssl/` 
`cd /etc/nginx/sites-available`
there should be config related to your domain name

here is the config file.
Change `rstormsf.dev` to your server name
```
server {
  set $site_name rstormsf.dev;

  listen 443 ssl spdy;
  ssl_certificate /etc/nginx/ssl/nginx.crt;
  ssl_certificate_key /etc/nginx/ssl/nginx.key;
  ssl_session_timeout 5m;
  ssl_session_cache shared:SSL:50m;

  ssl_dhparam /etc/nginx/ssl/dhparam.pem;
  ssl_protocols TLSv1.1 TLSv1.2;
  ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK';
  ssl_prefer_server_ciphers on;
  add_header Strict-Transport-Security max-age=15768000;
  ssl_stapling on;
  ssl_stapling_verify on;
  resolver 8.8.8.8;
  ssl_trusted_certificate /etc/nginx/ssl/nginx.crt;

  server_name  rstormsf.dev;
  access_log   /srv/www/rstormsf.dev/logs/rstormsf.dev.access.log;
  error_log    /srv/www/rstormsf.dev/logs/rstormsf.dev.error.log;

  root  /srv/www/rstormsf.dev/current/web;
  index index.php;

  charset utf-8;

  # See Virtualbox section at http://wiki.nginx.org/Pitfalls
    sendfile off;

  include wordpress.conf;
}

server {
  listen *:80;
  server_name www.rstormsf.dev;
  return 301 https://rstormsf.dev$request_uri;
}

server {
 listen *:80;
 server_name rstormsf.dev;
 return 301 https://rstormsf.dev$request_uri;
}
```

My next steps is to make it in ansible way and also update mysql(mariadb) configs to use over ssl connection (is it a good idea? )

**Comment by rstormsf** [comment]
@swalkinshaw 
Please take a look
https://github.com/rstormsf/bedrock-ansible/commit/ac207281808282bfc79e8508a136cefcce0b8ede

I'm still newbie with ansible, so I think I should also add commands to `copy/paste` actual certs which is provided in
https://github.com/rstormsf/bedrock-ansible/blob/master/roles/wordpress-setup/templates/wordpress-site.conf.j2#L6-L7

and also read file paths where to get it from, so a user can define it in `group_vars` 
Let me know your feedback, I can add those things to my second commit and can create PR to close this ticket.
1)How do we want to copy certs? Private key and public one.
2)How do we want to specify paths for our certs
3)What method should we use to send them? What is the best ansible task for that? Should we use file module?

**Comment by swalkinshaw** [comment]
@rstormsf that config looks mostly good. You have most of the good security and performance practices. Only thing missing is also adding the HSTS headers on the non SSL servers. Without it the redirects aren't fully secure.

You can also combine them:

```nginx
listen *:80;
server_name rstormsf.dev www.rstormsf.dev;
add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
return 301 https://rstormsf.dev$request_uri;
```

I'd use that version of HSTS header too above ^

Here's a few more settings you'll probably want:

```nginx
spdy_headers_comp 6;

# Staping
ssl_stapling on;
ssl_stapling_verify on;

resolver 8.8.8.8 8.8.4.4 216.146.35.35 216.146.36.36 valid=60s;
resolver_timeout 2s;

# longer session cache
ssl_session_cache    shared:SSL:10m; # a 1mb cache can hold about 4000 sessions, so we can hold 40000 sessions
ssl_session_timeout  24h;

# SSL buffer size was added in 1.5.9
ssl_buffer_size      1400; # 1400 bytes to fit in one MTU

ssl_session_tickets off;
# Use a higher keepalive timeout to reduce the need for repeated handshakes
keepalive_timeout 300; # up from 75 secs default
spdy_keepalive_timeout 300;
```

Answers:

1-3: Probably just let the paths to the key and crt be variables that need to be specified. I believe the `file` module is fine. It's only two files.

4:  Ansible tasks are designed to be idempotent meaning they can be re-run with no side effects. Even for SSL it's fine. The SSL role I implemented for roots.io gets run every day and there's no problem.

I'm thinking that I might just handle the SSL role since I already have most of it done. There's another one in https://github.com/roots/bedrock-ansible/pull/151 as well but it needs more comprehensive Nginx configs.

**Comment by rstormsf** [comment]
I see @swalkinshaw  - thank you very much for your detailed response. I'll continue working on it and will compare with the ssl role when you PR it to the repo.

**Comment by swalkinshaw** [comment]
See https://github.com/roots/bedrock-ansible/pull/172
