### ISSUE TITLE
Xdebug

### ISSUE THREAD

**Issue by nathanielks** [roots/bedrock-ansible#42]
Would you be at all opposed to including Xdebug in the mix as well?

**Comment by JacobDorman** [comment]
Any update on this? I could have a crack at it, or are we waiting on other changes to be merged?

**Comment by swalkinshaw** [comment]
@JacobDorman no update. Any work on it would be appreciated since I'm not too familiar with it. I don't think there's any ongoing work which was interfere with this.

**Comment by swalkinshaw** [comment]
Closed via https://github.com/roots/bedrock-ansible/pull/176
