### ISSUE TITLE
run PHP-FPM and friends under a common group

### ISSUE THREAD

**Issue by austinpray** [roots/bedrock-ansible#61]
re https://github.com/roots/bedrock-ansible/issues/30#issuecomment-56727697

In order for the `deploy` user to be able to restart PHP-fpm and friends via capistrano the web processes should be run under a common group. Common group could contain `deploy`, the `nginx` user, and whoever else needs to be at the party.

Thoughts?

**Comment by swalkinshaw** [comment]
Taken care of in https://github.com/roots/bedrock-ansible/pull/95

**Comment by austinpray** [comment]
Boom
