### ISSUE TITLE
add ssh-agent to startup

### ISSUE THREAD

**Issue by austinpray** [roots/bedrock-ansible#64]
Hey guys,

My `id_rsa` has a passphrase, as I am sure most of yours do. Running capistrano from the vagrant box (for db syncing and such) means I need to reconfigure and start my ssh-agent every time I boot or reprovision. 

What do you guys think about adding an ssh-agent configuration as a part of the provisioning process?

**Comment by swalkinshaw** [comment]
Added in 373fe77e90e5208fc96a9def301bb9e17b66f2ac
