### ISSUE TITLE
Use Ansible Galaxy Modules

### ISSUE THREAD

**Issue by nathanielks** [roots/bedrock-ansible#68]
Thinking about 3rd party integrations we'll eventually want/think about baking in: Digital Ocean Support, AWS, etc etc. Perhaps build them as separate modules and submit them to Ansible Galaxy so they can be installed via `ansible-galaxy`?

**Comment by MatthewMi11er** [comment]
@swalkinshaw if you haven't seen it already you should look into the [Debops](http://debops.org/) project. It has an excellent set of extremely thorough and well thought out Ansible roles for configuring a server. Personally, I would love to see bedrock integrated as an application into that stack.

**Comment by swalkinshaw** [comment]
@MatthewMi11er Debops is awesome but our issue with it is the GPL license.

**Comment by MatthewMi11er** [comment]
@swalkinshaw It's a shame that's an issue. Dealing with licenses can be a pain. Anyway, keep up the good work on this.

**Comment by swalkinshaw** [comment]
We're now doing as part of https://github.com/roots/bedrock-ansible/pull/95 and will be expanding to more roles.
